"""add role access table

Revision ID: 157b83656103
Revises: b77287ebd07b
Create Date: 2024-12-18 20:08:08.357012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '157b83656103'
down_revision: Union[str, None] = 'b77287ebd07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('patient_access', sa.String(), nullable=False),
    sa.Column('staff_access', sa.String(), nullable=False),
    sa.Column('resource_access', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.add_column('metric_definitions', sa.Column('unit', sa.String(length=50), nullable=True))
    op.add_column('metric_definitions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('metric_definitions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('metric_definitions_name_key', 'metric_definitions', type_='unique')
    op.drop_column('metric_definitions', 'display_name')
    op.drop_column('metric_definitions', 'data_type')
    op.drop_column('metric_definitions', 'category')
    op.drop_column('metric_definitions', 'aggregation_type')
    op.drop_column('metric_definitions', 'units')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('metric_definitions', sa.Column('units', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metric_definitions', sa.Column('aggregation_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metric_definitions', sa.Column('category', postgresql.ENUM('PATIENT', 'STAFF', name='metriccategory'), autoincrement=False, nullable=False))
    op.add_column('metric_definitions', sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('metric_definitions', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('metric_definitions_name_key', 'metric_definitions', ['name'])
    op.drop_column('metric_definitions', 'updated_at')
    op.drop_column('metric_definitions', 'created_at')
    op.drop_column('metric_definitions', 'unit')
    op.drop_table('role_access')
    # ### end Alembic commands ###
