"""add session table

Revision ID: 87f072926187
Revises: add_default_roles
Create Date: 2024-12-19 15:33:23.696517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f072926187'
down_revision: Union[str, None] = 'add_default_roles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('sessions', 'last_activity')
    op.drop_column('sessions', 'session_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'is_active')
    op.drop_column('sessions', 'updated_at')
    # ### end Alembic commands ###
