"""Fix relationships

Revision ID: e5376424f672
Revises: 307b9bf97421
Create Date: 2024-12-17 22:34:06.226760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5376424f672'
down_revision: Union[str, None] = '307b9bf97421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_metrics', sa.Column('is_calculated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_metrics', 'is_calculated')
    # ### end Alembic commands ###
